<?php

// Include PhpSpreadsheet library
require 'vendor/autoload.php'; // Adjust the path according to your project structure

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Assuming $majors, $kelas, $madin, $setting_school, $setting_address, $setting_phone, and $student are properly defined before this point

$filename = 'Data_Siswa_' . $majors['majors_short_name'] . '_Kelas_' . $kelas['class_name'] . '_Kelas Pondok_' . $madin['madin_name'];

// Create a new PhpSpreadsheet instance
$spreadsheet = new Spreadsheet();

// Set document properties
$spreadsheet->getProperties()
    ->setCreator('Your Name')
    ->setTitle($filename)
    ->setDescription('Generated by PHPExcel');

// Create a worksheet and set column headers
$worksheet = $spreadsheet->getActiveSheet();
$worksheet->setCellValue('A1', 'No.')
    ->setCellValue('B1', 'NIS')
    ->setCellValue('C1', 'Nama Lengkap')
    ->setCellValue('D1', 'Jenis Kelamin')
    ->setCellValue('E1', 'Kelas')
    ->setCellValue('F1', 'Kelas Pondok')
    ->setCellValue('G1', 'Alamat')
    ->setCellValue('H1', 'Nama Ayah')
    ->setCellValue('I1', 'Nama Ibu')
    ->setCellValue('J1', 'No. HP/Telpon Ortu');

// Populate data from $student array
$i = 2; // Start from the second row
foreach ($student as $row) {
    $worksheet->setCellValue('A' . $i, $i - 1)
        ->setCellValueExplicit('B' . $i, $row['student_nis'], \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING)
        ->setCellValue('C' . $i, $row['student_full_name'])
        ->setCellValue('D' . $i, $row['student_gender'])
        ->setCellValue('E' . $i, $row['class_name'])
        ->setCellValue('F' . $i, $row['madin_name'])
        ->setCellValue('G' . $i, $row['student_address'])
        ->setCellValue('H' . $i, $row['student_name_of_father'])
        ->setCellValue('I' . $i, $row['student_name_of_mother'])
        ->setCellValueExplicit('J' . $i, $row['student_parent_phone'], \PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);

    $i++;
}

// Set headers for download
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $filename . '.xlsx"');
header('Cache-Control: max-age=0');

// Create Excel writer
$writer = new Xlsx($spreadsheet);

// Save the file to php://output (output to browser)
$writer->save('php://output');
